### ISSUE TITLE
Crawl all stickers on the entire site?

### ISSUE THREAD

**Issue by chaoscreater** [curegit/line-sticker-downloader#1]
Is it possible to download all stickers on the entire site in one go?

**Comment by curegit** [comment]
Unfortunately, no. You have to specify sticker IDs one by one.

**Comment by chaoscreater** [comment]
Would you be able to add the "download all stickers" as a feature please?

**Comment by curegit** [comment]
How about using shell?
I will change the script able to be used with CLI PHP so that iterate IDs by shell.
Downloading and zipping many stickers is too heavy for CGI.

**Comment by chaoscreater** [comment]
Sure, I'll take anything! I'll just need some basic instructions to get it set up and running :)

**Comment by chaoscreater** [comment]
Any luck with this?

**Comment by curegit** [comment]
Yeah, almost done. A few tasks are left. 

I will update Readme later.

**Comment by curegit** [comment]
Done. 

Now you can try like this.
https://github.com/curegit/line-sticker-downloader#download-multiple-sticker-packages

**Comment by chaoscreater** [comment]
Awesome, you're amazing. Will test it out now.

**Comment by chaoscreater** [comment]
Is it possible to specify only Android stickers to be downloaded, for both individual download and mass/batch download?

And is it possible to do run multiple jobs at the same time? It seems that the loop is waiting for each one to be completed before running the next one. Ideally, I would like to run 2~8 downloads concurrently at a time.

Could you please also update this in the Readme, might help Windows users:

1. Download and install php.exe
2. Add php to environmental variables path
3. Unzip the project somewhere, e.g. D:\
4. Run powershell and cd to D:\
5. Run the following:

for($i = 1; $i -lt 1000000; $i++){ 
	php download.php $i
}

**Comment by curegit** [comment]
Thanks for your review. 

I think changing code to specify target device is not so hard.

It is tiring to change the php code for concurrency, so please try running multiple processes.

**Comment by curegit** [comment]
I changed my mind.

Making device-partial downloading possible gets cache handling difficult.

If you really want to do so, change script like below

change download.php line 134
```php
  // Devices array
  $profiles = array("iPhone", "android", "WindowsPhone", "PC");
```
to
```php
  // Devices array
  $profiles = array("android");
```

**Comment by chaoscreater** [comment]
Yeah I figured that out when I was going over your code. Ideally I'd like to focus on getting the multi-thread downloads working, but I have no idea how to code it. You mentioned running multiple processes, but that also means I need to change the starting index "i" in the code for every new process, instead of just calling like 10 different concurrent jobs in the same process.

**Comment by curegit** [comment]
I found using xargs was a easy way for Bash.

```bash
for ((i=3200; i<3300; i++)); do echo $i; done | xargs -P 8 -L 1 php download.php
```

However, I don't know how to do what is same thing in other environments.
